namespace Origo.Bifrost.Inventory;

codeunit 70013430 "Transfer Order Create Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Inventory.TransferOrder.Create - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Creates a transfer order: the header with its from, to and in-transit locations and, when `lines` is sent, its lines in the same call. Without `lines` only the header is created.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (write)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Not idempotent**: each call creates a new transfer order and uses a number from the Transfer Order No. Series.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `transferFromCode` | string | Yes | Source location (Code[10]). |');
        HelpBuilder.AppendLine('| `transferToCode` | string | Yes | Destination location (Code[10]). |');
        HelpBuilder.AppendLine('| `directTransfer` | bool | No | `true` for a direct transfer without an in-transit step. Default `false`; `true` or `false`, any other value is an error. |');
        HelpBuilder.AppendLine('| `inTransitCode` | string | When `directTransfer` is `false` | In-transit location (Code[10]). |');
        HelpBuilder.AppendLine('| `postingDate` | date | No | `YYYY-MM-DD`. The work date when omitted. |');
        HelpBuilder.AppendLine('| `shipmentDate` | date | No | `YYYY-MM-DD`. Blank when omitted. |');
        HelpBuilder.AppendLine('| `receiptDate` | date | No | `YYYY-MM-DD`. Blank when omitted. |');
        HelpBuilder.AppendLine('| `externalDocumentNo` | string | No | External document number (Code[35]). |');
        HelpBuilder.AppendLine('| `lines` | object[] | No | The transfer lines, at most 200. See **With lines**. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('All three dates are read before the call stops, so every bad date is reported in one answer.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## With lines');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('The call is all-or-nothing. Every line is checked before the header is created, and every problem is reported in one answer, so nothing is created when one line is wrong. An error that BC raises while validating a line also rolls back the whole call: the header and the lines before it are not kept.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- Field names are camelCase. Foundation assigns the line numbers (10000, 20000, ...); do not send `lineNo`.');
        HelpBuilder.AppendLine('- A request can contain at most 200 lines.');
        HelpBuilder.AppendLine('- The index in an error is 1-based: `lines[1]` is the first line.');
        HelpBuilder.AppendLine('- Transfer lines have no type and no price.');
        HelpBuilder.AppendLine('- Validation order (the order BC validates the fields in): Item No., Variant Code, Unit of Measure Code, Quantity, Shipment Date, Description.');
        HelpBuilder.AppendLine('- A field you leave out keeps its BC default. A field you send overrides it.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Field | Type | Required | Description |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| itemNo | Text | Yes | Item number. It must exist and not be blocked. |');
        HelpBuilder.AppendLine('| variantCode | Text | No | Item variant. It must exist for the item. |');
        HelpBuilder.AppendLine('| unitOfMeasureCode | Text | No | Unit of measure of the item. The base unit when omitted. |');
        HelpBuilder.AppendLine('| quantity | Decimal | Yes | Quantity in `unitOfMeasureCode`. |');
        HelpBuilder.AppendLine('| shipmentDate | Date | No | `YYYY-MM-DD`. The header shipment date when omitted. |');
        HelpBuilder.AppendLine('| description | Text | No | Line description. BC fills it from the item when omitted. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "type": "Inventory.TransferOrder.Create",');
        HelpBuilder.AppendLine('  "data": {');
        HelpBuilder.AppendLine('    "transferFromCode": "BLUE",');
        HelpBuilder.AppendLine('    "transferToCode": "RED",');
        HelpBuilder.AppendLine('    "inTransitCode": "OWN LOG.",');
        HelpBuilder.AppendLine('    "lines": [');
        HelpBuilder.AppendLine('      { "itemNo": "1896-S", "quantity": 2, "unitOfMeasureCode": "PCS" },');
        HelpBuilder.AppendLine('      { "itemNo": "1900-S", "quantity": 1 }');
        HelpBuilder.AppendLine('    ]');
        HelpBuilder.AppendLine('  }');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Without lines');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Only the header is created. A transfer order cannot be released without lines, so send them on this call when you have them.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "type": "Inventory.TransferOrder.Create",');
        HelpBuilder.AppendLine('  "data": { "transferFromCode": "BLUE", "transferToCode": "RED", "directTransfer": true }');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "documentNo": "TO000456",');
        HelpBuilder.AppendLine('  "systemId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",');
        HelpBuilder.AppendLine('  "transferFromCode": "BLUE",');
        HelpBuilder.AppendLine('  "transferToCode": "RED",');
        HelpBuilder.AppendLine('  "inTransitCode": "OWN LOG.",');
        HelpBuilder.AppendLine('  "directTransfer": false,');
        HelpBuilder.AppendLine('  "postingDate": "2026-09-27",');
        HelpBuilder.AppendLine('  "shipmentDate": "2026-09-27",');
        HelpBuilder.AppendLine('  "receiptDate": "2026-09-27",');
        HelpBuilder.AppendLine('  "externalDocumentNo": "",');
        HelpBuilder.AppendLine('  "statusAfter": "Open",');
        HelpBuilder.AppendLine('  "lines": [');
        HelpBuilder.AppendLine('    { "lineNo": 10000, "itemNo": "1896-S", "description": "ATHENS Desk", "quantity": 2, "unitOfMeasureCode": "PCS" }');
        HelpBuilder.AppendLine('  ],');
        HelpBuilder.AppendLine('  "totals": { "quantity": 3 }');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Property | Description |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `status` | `Success`. |');
        HelpBuilder.AppendLine('| `documentNo` / `systemId` | The new transfer order. |');
        HelpBuilder.AppendLine('| `transferFromCode` / `transferToCode` / `inTransitCode` / `directTransfer` | The header values after BC validation. |');
        HelpBuilder.AppendLine('| `postingDate` / `shipmentDate` / `receiptDate` | `YYYY-MM-DD`. |');
        HelpBuilder.AppendLine('| `externalDocumentNo` | Empty when not sent. |');
        HelpBuilder.AppendLine('| `statusAfter` | Always `Open`. |');
        HelpBuilder.AppendLine('| `lines[]` | Only with `lines`: each created line with `lineNo`, `itemNo`, `description`, `quantity` and `unitOfMeasureCode`. |');
        HelpBuilder.AppendLine('| `totals` | Only with `lines`: the total `quantity`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Code | Error | Cause |');
        HelpBuilder.AppendLine('|---|---|---|');
        HelpBuilder.AppendLine('| `MissingParameter` | `transferFromCode must be specified in the request JSON.` | `transferFromCode` was not sent. |');
        HelpBuilder.AppendLine('| `MissingParameter` | `transferToCode must be specified in the request JSON.` | `transferToCode` was not sent. |');
        HelpBuilder.AppendLine('| `MissingParameter` | `inTransitCode must be specified when directTransfer is false.` | No `inTransitCode` for a transfer that is not direct. |');
        HelpBuilder.AppendLine('| `InvalidParameterFormat` | `Parameter "{name}" has value "{value}", which is not a valid {type}. Expected {format}.` | A date is not `YYYY-MM-DD`, or `directTransfer` is not `true` or `false`. Several bad values are reported together. |');
        HelpBuilder.AppendLine('| `InvalidLine` | `{n} problem(s) in lines. Nothing was created.` | The pre-check found problems. `errors[]` lists each one with `parameter` `lines[n].<field>`: `MissingParameter` (`<field> is required.`), `InvalidParameterFormat` (not a number or not a date), `InvalidParameter` (not a valid option), `RecordNotFound` (the item, account or other record does not exist) or `PreconditionFailed` (it is blocked). With one problem, that problem is the answer and there is no `errors[]`. |');
        HelpBuilder.AppendLine('| `BusinessCentralError` | `lines[n].<field>: <BC error>` | BC rejected a value while validating line `n`. `parameter` is `lines[n].<field>`. Nothing was created, not even the header. |');
        HelpBuilder.AppendLine('| `LimitExceeded` | `A request can contain at most 200 lines. Received: {n}.` | More than 200 lines. `received` is the count, `expected` is `200`. |');
        HelpBuilder.AppendLine('| `InvalidParameterFormat` | `lines must be an array.` | `lines` is not a JSON array. |');
        HelpBuilder.AppendLine('| `BusinessCentralError` | (BC error text) | BC rejected the header, for example an unknown location or equal from and to codes. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Typical Workflow');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `Inventory.TransferOrder.Create` with `lines`.');
        HelpBuilder.AppendLine('2. `Inventory.TransferOrder.Release`: release the order.');
        HelpBuilder.AppendLine('3. `Inventory.TransferOrder.PreviewPost`: optional, see the entries without posting.');
        HelpBuilder.AppendLine('4. `Inventory.TransferOrder.Post`: ship and receive.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Inventory.TransferOrder.Release`: release once the order has lines.');
        HelpBuilder.AppendLine('- `Inventory.TransferOrder.PreviewPost` / `Inventory.TransferOrder.Post`: simulate or post.');
        HelpBuilder.AppendLine('- `Inventory.TransferOrder.Statistics`: read the totals.');
        HelpBuilder.AppendLine('- `Data.Records.Set`: change header fields. Lines belong on `Inventory.TransferOrder.Create`.');
        HelpText := HelpBuilder.ToText();
    end;
}
