namespace Origo.Bifrost.Inventory;

codeunit 70013429 "Transf Doc Prev. Post Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Inventory.TransferOrder.PreviewPost - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('Simulates posting a Transfer Order and returns the captured ledger entries (Item Ledger, Value Entry, G/L Entry where applicable) without committing. Uses BC `Gen. Jnl.-Post Preview.SetContext(TransferOrder-Post, TransferHeader)` then `Run()` with the `Transfer Post Subscriber` injecting the chosen ship/receive/transfer options.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Idempotency / Safety');
        HelpBuilder.AppendLine('Safe and idempotent. The transaction is always rolled back. No Posted Transfer Shipment / Receipt rows, ledger entries, or No. Series numbers persist after the call. `rollback: true` is included in every successful response to make this explicit.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Order Identification');
        HelpBuilder.AppendLine('Standard `Transfer Header` identification:');
        HelpBuilder.AppendLine('1. `subject` parsed as GUID -> header `SystemId`.');
        HelpBuilder.AppendLine('2. `subject` as text -> header `No.`.');
        HelpBuilder.AppendLine('3. Request JSON keys (every key supplied is tried; identifiers that point to different records are refused): `systemId`, `recordSystemId`, `id`, `documentNo`, `transferOrderNo`, `no`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('| Field | Type | Required | Description |');
        HelpBuilder.AppendLine('|-------|------|----------|-------------|');
        HelpBuilder.AppendLine('| postingType | Text | Required for non-direct transfers, ignored for direct | `"Ship"` or `"Receive"` (case-insensitive). |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Examples');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "type": "Inventory.TransferOrder.PreviewPost",');
        HelpBuilder.AppendLine('  "subject": "TO000456",');
        HelpBuilder.AppendLine('  "data": { "postingType": "Ship" }');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "entryCount": 2,');
        HelpBuilder.AppendLine('  "glEntryCount": 0,');
        HelpBuilder.AppendLine('  "rollback": true,');
        HelpBuilder.AppendLine('  "summary": "Transfer Order TO000456 (BLUE -> RED) Ship preview produced 2 entries. No G/L entries would be posted.",');
        HelpBuilder.AppendLine('  "documentNo": "TO000456",');
        HelpBuilder.AppendLine('  "transferFromCode": "BLUE",');
        HelpBuilder.AppendLine('  "transferToCode": "RED",');
        HelpBuilder.AppendLine('  "directTransfer": false,');
        HelpBuilder.AppendLine('  "postingType": "Ship",');
        HelpBuilder.AppendLine('  "lcyCode": "USD",');
        HelpBuilder.AppendLine('  "predictedNumbers": { "postedShipmentNo": "PTS00012" },');
        HelpBuilder.AppendLine('  "totals": { "totalDebitLCY": 0, "totalCreditLCY": 0 },');
        HelpBuilder.AppendLine('  "preview": [');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "tableId": 32,');
        HelpBuilder.AppendLine('      "tableName": "Item Ledger Entry",');
        HelpBuilder.AppendLine('      "tableCaption": "Item Ledger Entry",');
        HelpBuilder.AppendLine('      "entryCount": 2,');
        HelpBuilder.AppendLine('      "entries": [');
        HelpBuilder.AppendLine('        {');
        HelpBuilder.AppendLine('          "id": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('          "primaryKey": { "EntryNo_": "1" },');
        HelpBuilder.AppendLine('          "fields": { "ItemNo_": "1000", "DocumentNo_": "PTS00012", "Quantity": "-1" }');
        HelpBuilder.AppendLine('        }');
        HelpBuilder.AppendLine('      ]');
        HelpBuilder.AppendLine('    }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Property | Description |');
        HelpBuilder.AppendLine('|----------|-------------|');
        HelpBuilder.AppendLine('| status | `Success` whenever the preview completed; `Error` if preview itself threw. |');
        HelpBuilder.AppendLine('| rollback | Always `true`. |');
        HelpBuilder.AppendLine('| entryCount | On every Success answer: the number of captured entries. |');
        HelpBuilder.AppendLine('| glEntryCount | On every Success answer: the number of captured G/L entries. `0` when the posting creates no G/L entry. |');
        HelpBuilder.AppendLine('| summary | Human-readable one-liner. When `glEntryCount` is 0 it ends with "No G/L entries would be posted." The balanced sentence is used only when G/L entries were captured. |');
        HelpBuilder.AppendLine('| documentNo / transferFromCode / transferToCode / directTransfer | Echo of header fields. |');
        HelpBuilder.AppendLine('| postingType | `Ship`, `Receive`, or `DirectTransfer`. |');
        HelpBuilder.AppendLine('| lcyCode | `General Ledger Setup."LCY Code"`. |');
        HelpBuilder.AppendLine('| predictedNumbers | One of `postedShipmentNo` / `postedReceiptNo` / `postedDirectTransferNo` depending on the posting type. Empty string when nothing predicted. |');
        HelpBuilder.AppendLine('| totals.balanced | Present only when G/L entries were captured (`glEntryCount > 0`): `true` when `Round(totalDebitLCY - totalCreditLCY, 0.01) = 0`. Omitted when the posting creates no G/L entry. |');
        HelpBuilder.AppendLine('| totals.totalDebitLCY / totals.totalCreditLCY | Sums of G/L Entry debit/credit (LCY). |');
        HelpBuilder.AppendLine('| preview[] | One element per captured table. Each element has `tableId`, `tableName`, `tableCaption`, `entryCount` and `entries`. |');
        HelpBuilder.AppendLine('| preview[].entries[] | Per-entry objects with `id`, `primaryKey` and `fields`. Field names follow the same normalization as `Data.Records.Get`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Preview Outcome');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('The preview answers `Success` only when it captured at least one entry. Every Success answer carries `entryCount` (all captured entries) and `glEntryCount` (the G/L entries among them).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Nothing would be posted** (no entry captured, or BC reports that there is nothing to post): `status: Error`, `code: NothingToPreview`, `error: "The preview produced no entries. Nothing would be posted."` and a `nextStep`: No line has a quantity to ship or receive. Review with `Inventory.TransferOrder.Statistics`.');
        HelpBuilder.AppendLine('- **No G/L entries** (for example item or value entries with Automatic Cost Posting off): `Success` with `glEntryCount: 0` and **no** `totals.balanced`; the summary says "No G/L entries would be posted."');
        HelpBuilder.AppendLine('- **G/L entries**: `totals.balanced` as described above.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('A Business Central posting error raised during the preview is returned verbatim, with no `code`. The catch-all below is used only when the preview run fails and Business Central returns no error text. A preview that runs and captures no entries is `NothingToPreview`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|-------|-------|');
        HelpBuilder.AppendLine('| `The preview produced no entries. Nothing would be posted.` (`NothingToPreview`) | Nothing would be posted. `nextStep`: No line has a quantity to ship or receive. Review with `Inventory.TransferOrder.Statistics`. |');
        HelpBuilder.AppendLine('| `Transfer Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, documentNo, transferOrderNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Transfer Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `"{value}" is not a valid GUID` / `integer` `(from {key}).` (`InvalidParameterFormat`) | A SystemId or entry number that cannot be read. |');
        HelpBuilder.AppendLine('| `Transfer order {No.} has no lines to post.` (`NothingToPreview`) | The order has no `Transfer Line` rows. `nextStep`: No line has a quantity to ship or receive. Review with `Inventory.TransferOrder.Statistics`. |');
        HelpBuilder.AppendLine('| `For a non-direct transfer order, postingType must be "Ship" or "Receive".` | Non-direct transfer and `postingType` omitted. Returned with no `code`. |');
        HelpBuilder.AppendLine('| `postingType must be "Ship" or "Receive". Received: {value}` | `postingType` had an unsupported value. Returned with no `code`. |');
        HelpBuilder.AppendLine('| `Posting preview failed and no entries were captured. The transfer order cannot be posted in its current state.` | The preview run failed and Business Central returned no error text. Returned with no `code`. |');
        HelpBuilder.AppendLine('| Business Central posting error text | Any other error raised by `TransferOrder-Post (Yes/No)` under `Gen. Jnl.-Post Preview`. Returned verbatim, with no `code`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('- `Inventory.TransferOrder.Post` - actually post once preview is clean.');
        HelpBuilder.AppendLine('- `Inventory.TransferOrder.Statistics` - inspect totals.');

        HelpText := HelpBuilder.ToText();
    end;
}
