namespace Origo.Bifrost.Inventory;

codeunit 70013438 "Assembly Order Create Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Inventory.AssemblyOrder.Create - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('Creates a new Assembly Order (Assembly Header with `Document Type = Order`) for a parent item. The header `No.` is assigned from the Assembly Order No. Series. By default the component lines are refreshed from the parent item BOM via `Item No.` re-validation.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Idempotency / Safety');
        HelpBuilder.AppendLine('Not idempotent. Every call inserts a new Assembly Order header and consumes one number from the Assembly Order No. Series, and (when `refreshLines = true`, the default) re-creates component lines from the BOM.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('| Field | Type | Required | Description |');
        HelpBuilder.AppendLine('|-------|------|----------|-------------|');
        HelpBuilder.AppendLine('| itemNo | Code[20] | Yes | Parent (assembled) item number. |');
        HelpBuilder.AppendLine('| quantity | Decimal | Yes | JSON number, or a string with `.` and no thousands separator. Must be `> 0`. An invalid value is an error. |');
        HelpBuilder.AppendLine('| variantCode | Code[10] | No | Item variant. |');
        HelpBuilder.AppendLine('| locationCode | Code[10] | No | Output location. |');
        HelpBuilder.AppendLine('| binCode | Code[20] | No | Output bin within the location. Applied after `Quantity`. |');
        HelpBuilder.AppendLine('| unitOfMeasureCode | Code[10] | No | UoM of the parent item. |');
        HelpBuilder.AppendLine('| description | Text[100] | No | Header description. |');
        HelpBuilder.AppendLine('| postingDate | Date | No | `YYYY-MM-DD`. Omitted: `WorkDate()`. An invalid value is an error. |');
        HelpBuilder.AppendLine('| dueDate | Date | No | `YYYY-MM-DD`. Omitted: blank. An invalid value is an error. |');
        HelpBuilder.AppendLine('| startingDate | Date | No | `YYYY-MM-DD`. Omitted: blank. An invalid value is an error. |');
        HelpBuilder.AppendLine('| endingDate | Date | No | `YYYY-MM-DD`. Omitted: blank. An invalid value is an error. |');
        HelpBuilder.AppendLine('| quantityToAssemble | Decimal | No | JSON number, or a string with `.` and no thousands separator. Applied only when `> 0`; otherwise BC default (= `Quantity`) is kept. An invalid value is an error. |');
        HelpBuilder.AppendLine('| refreshLines | Boolean | No | When `true` (default), re-validates `Item No.` after the initial validate to refresh component lines from the BOM. Set `false` to skip the BOM refresh. `true` or `false`; any other value is an error. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "type": "Inventory.AssemblyOrder.Create",');
        HelpBuilder.AppendLine('  "data": {');
        HelpBuilder.AppendLine('    "itemNo": "BICYCLE",');
        HelpBuilder.AppendLine('    "quantity": 5,');
        HelpBuilder.AppendLine('    "locationCode": "BLUE",');
        HelpBuilder.AppendLine('    "dueDate": "2026-05-30",');
        HelpBuilder.AppendLine('    "refreshLines": true');
        HelpBuilder.AppendLine('  }');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "documentNo": "AO000123",');
        HelpBuilder.AppendLine('  "systemId": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('  "itemNo": "BICYCLE",');
        HelpBuilder.AppendLine('  "variantCode": "",');
        HelpBuilder.AppendLine('  "description": "Bicycle",');
        HelpBuilder.AppendLine('  "locationCode": "BLUE",');
        HelpBuilder.AppendLine('  "binCode": "",');
        HelpBuilder.AppendLine('  "unitOfMeasureCode": "PCS",');
        HelpBuilder.AppendLine('  "quantity": 5,');
        HelpBuilder.AppendLine('  "quantityToAssemble": 5,');
        HelpBuilder.AppendLine('  "postingDate": "2026-04-15",');
        HelpBuilder.AppendLine('  "dueDate": "2026-05-30",');
        HelpBuilder.AppendLine('  "startingDate": "2026-04-15",');
        HelpBuilder.AppendLine('  "endingDate": "2026-05-30",');
        HelpBuilder.AppendLine('  "statusAfter": "Open",');
        HelpBuilder.AppendLine('  "lineCount": 3');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Property | Description |');
        HelpBuilder.AppendLine('|----------|-------------|');
        HelpBuilder.AppendLine('| status | `Success`. Validation failures use the standard error envelope. |');
        HelpBuilder.AppendLine('| documentNo | New `Assembly Header.No.` (from No. Series). |');
        HelpBuilder.AppendLine('| systemId | New header `SystemId` (Format `0,4`, no braces). |');
        HelpBuilder.AppendLine('| itemNo / variantCode / description / locationCode / binCode / unitOfMeasureCode | Header echo after BC validation (may differ from request if defaults applied). |');
        HelpBuilder.AppendLine('| quantity / quantityToAssemble | Header values after validation. |');
        HelpBuilder.AppendLine('| postingDate / dueDate / startingDate / endingDate | Format `0,9` (`yyyy-MM-dd`). BC computes the dates not supplied explicitly. |');
        HelpBuilder.AppendLine('| statusAfter | `Open` (newly created orders are always Open). |');
        HelpBuilder.AppendLine('| lineCount | Number of `Assembly Line` rows. `0` when `refreshLines = false`, otherwise the BOM line count. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|-------|-------|');
        HelpBuilder.AppendLine('| `itemNo must be specified in the request JSON.` | `itemNo` missing or empty. |');
        HelpBuilder.AppendLine('| `quantity must be specified and greater than 0 in the request JSON.` | `quantity` missing or `<= 0`. |');
        HelpBuilder.AppendLine('| (BC validation error text) | Any `Validate` call surfaced an error (unknown item, invalid location, missing BOM, etc.). Caught and returned in `error`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('- `Inventory.AssemblyOrder.RefreshLines` - refresh BOM lines on an existing order.');
        HelpBuilder.AppendLine('- `Inventory.AssemblyOrder.Release` - release an Open order.');
        HelpBuilder.AppendLine('- `Inventory.AssemblyOrder.Post` - post.');
        HelpBuilder.AppendLine('- `Inventory.AssemblyOrder.PreviewPost` - dry run.');
        HelpBuilder.AppendLine('- `Data.Records.Set` - adjust component lines.');

        HelpText := HelpBuilder.ToText();
    end;
}
